title: 디케이앤트
email: bearkim@dkant.net
description: |
  AI, Network, Technology.
  
  디케이앤트는
  사물과 사물, 사물과 사람, 사람과 사람 간을 연결하는 기술을 연구해
  사회에 도움이 되고자 합니다.
baseurl: ''
url: 'https://dkant.net'
timezone: Asia/Seoul 

repository: dkantech/dkantech.github.io

permalink: /:year/:month/:day/:title/

excerpt_separator: <!--more-->

markdown: kramdown

krandown:
  input: GFM
  highlighter: rouge

plugins:
  - jekyll-paginate

paginate: 5
paginate_path: '/technote/:num/'

collections:
  authors:
    output: true
    permalink: /authors/:path/
  tags:
    output: true
    permalink: /tags/:path/

defaults:
  - scope:
      path: ''
      type: authors
    values:
      layout: author
  - scope:
      path: ''
      type: tags
    values:
      layout: tag


keep_files: [assets, files]
github: [metadata]
# iolo's custom
author: bearkim@dkant.net
image: '/assets/images/default_blog_cover.png'
asset_url: /assets
#asset_url: //meta-kage.kakaocdn.net/dn/osa/blog/assets
#asset_url: //t1.daumcdn.net/osa/blog/assets
google_analytics:
  ua: 'UA-142770354-1'
# facebook:
#   app_id: '1204347326263800'
#   username: nkakao
# twitter:
#   username: kakaodev
# google_plus:
#   username: kakaodev
github_url:
  username: dkantech

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - any_additional_item
